// Map OpenF1 circuit_short_name → Jolpica circuitId
export const CIRCUIT_MAP: Record<string, string> = {
  Bahrain: "bahrain",
  Jeddah: "jeddah",
  Melbourne: "albert_park",
  Suzuka: "suzuka",
  Shanghai: "shanghai",
  Miami: "miami",
  Imola: "imola",
  Monaco: "monaco",
  Barcelona: "catalunya",
  Montreal: "villeneuve",
  Spielberg: "red_bull_ring",
  Silverstone: "silverstone",
  Budapest: "hungaroring",
  "Spa-Francorchamps": "spa",
  Zandvoort: "zandvoort",
  Monza: "monza",
  Baku: "baku",
  Singapore: "marina_bay",
  Austin: "americas",
  "Mexico City": "rodriguez",
  "São Paulo": "interlagos",
  "Las Vegas": "vegas",
  Lusail: "losail",
  "Yas Island": "yas_marina",
};
